<?php
/**
 * KloudStack Migration — Background Export Engine
 *
 * Manages async jobs for DB dump and per-file media upload to Azure Blob Storage.
 * Uses WP-Cron for scheduling: process_queue() runs every 60 seconds.
 *
 * Job lifecycle:
 *   queued → processing → complete | failed
 *
 * DB export:
 *   1. Shell-out to mysqldump --single-transaction --quick (respects WP DB constants)
 *   2. Write raw SQL to a temp file (no gzip — avoids CPU spike on shared hosting)
 *   3. Upload the SQL dump to Azure Blob via SAS PUT request
 *   4. Update job transient → complete
 *
 * Media upload (per-file streaming — Sprint M):
 *   1. Enumerate all files in wp-content/uploads/ recursively
 *   2. For each file: cURL PUT directly to Azure Blob using a container-level SAS token
 *      — no ZIP, no /tmp disk usage, no compression
 *   3. Track uploaded files in the job transient for resume-on-retry (checkpointed)
 *   4. After all files: upload a _manifest.json blob to signal completion
 *   5. Update job transient → complete
 *
 * Content export (plugins / themes / mu-plugins / custom-root):
 *   1. Create a ZIP archive of the source directory
 *   2. Stream upload to Azure Blob via SAS PUT request
 *   3. Update job transient → complete
 *
 * Security:
 *   - mysqldump credentials taken from WP_DB_* constants (never user input)
 *   - Command arguments individually escaped with escapeshellarg()
 *   - SAS URLs and SAS tokens validated to be HTTPS / Azure Blob endpoints before use
 *   - Temp files created in sys_get_temp_dir() with unique names and deleted after use
 *
 * @package KloudStackMigration
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class KloudStack_Migration_BackgroundExport {

    const CRON_HOOK    = 'kloudstack_process_export_queue';
    const QUEUE_OPTION = 'kloudstack_export_queue';

    // Max jobs processed per cron tick / shutdown call.
    // Set high enough to drain all content_export jobs (plugins + themes + mu-plugins)
    // in a single pass — critical for hosts with DISABLE_WP_CRON=true where only one
    // shutdown-function invocation fires and WP-Cron never picks up remaining jobs.
    const MAX_JOBS_PER_RUN = 10;

    // Chunk size for streaming upload: 4 MB
    const UPLOAD_CHUNK_SIZE = 4 * 1024 * 1024;

    // ------------------------------------------------------------------
    // Cron setup
    // ------------------------------------------------------------------

    public static function setup_cron(): void {
        if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
            wp_schedule_event( time(), 'every_minute', self::CRON_HOOK );
        }
        add_filter( 'cron_schedules', [ __CLASS__, 'add_cron_interval' ] );
        add_action( self::CRON_HOOK, [ __CLASS__, 'process_queue' ] );
    }

    public static function add_cron_interval( array $schedules ): array {
        if ( ! isset( $schedules['every_minute'] ) ) {
            $schedules['every_minute'] = [
                'interval' => 60,
                'display'  => 'Every Minute',
            ];
        }
        return $schedules;
    }

    // ------------------------------------------------------------------
    // Queue management
    // ------------------------------------------------------------------

    /**
     * Enqueue a new export job.
     *
     * @param string $job_id     Unique job ID (generated by RestEndpoints)
     * @param string $type       'db_export' | 'media_upload' | 'content_export'
     * @param string $sas_url    Azure Blob SAS URL for uploading
     * @param array  $extra_data Additional fields to store in the queue item (e.g. source_path, artifact)
     */
    public static function enqueue( string $job_id, string $type, string $sas_url, array $extra_data = [] ): void {
        $queue   = get_option( self::QUEUE_OPTION, [] );
        $queue[] = array_merge(
            [
                'job_id'  => $job_id,
                'type'    => $type,
                'sas_url' => $sas_url,
            ],
            $extra_data
        );
        update_option( self::QUEUE_OPTION, $queue, false );
    }

    /**
     * Process the next job(s) from the queue.
     * Called by WP-Cron every minute.
     */
    public static function process_queue(): void {
        global $wpdb;

        // DB-level mutex using INSERT IGNORE — works in shutdown context where
        // set_transient() / get_transient() fail because the object cache (APCu, W3TC,
        // Redis) is closed by WordPress's own shutdown hook before ours runs (PHP FIFO).
        // A transient-based lock is silently a no-op here, allowing concurrent execution.
        $lock_name = 'ks_mig_queue_lock';
        $now       = time();

        $acquired = (bool) $wpdb->query( $wpdb->prepare(
            "INSERT IGNORE INTO {$wpdb->options} (option_name, option_value, autoload) VALUES (%s, %s, 'no')",
            $lock_name,
            (string) $now
        ) );

        if ( ! $acquired ) {
            // Row exists — check if it is stale (process was killed before finally released it).
            $lock_ts = (int) $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                $lock_name
            ) );
            if ( $lock_ts > 0 && ( $now - $lock_ts ) < 600 ) {
                return; // Fresh lock — another invocation is running.
            }
            // Stale lock (> 10 min) — force-claim it so a killed process cannot block forever.
            $wpdb->update( $wpdb->options, [ 'option_value' => (string) $now ], [ 'option_name' => $lock_name ] );
        }

        try {
            // Read the queue directly from DB, bypassing the WordPress object cache.
            //
            // get_option() returns from the per-process in-memory cache first.  When two
            // PHP-FPM workers handle concurrent REST requests (e.g. Worker A for
            // export-site-content, Worker B for upload-media), each worker's cache only
            // reflects its OWN update_option() calls.  Worker A's cache has [plugins, themes];
            // Worker B wrote [plugins, themes, media] to DB afterwards but Worker A's cache
            // never received that update.  Calling get_option() in Worker A's shutdown
            // therefore returns stale [plugins, themes], and the media job is silently wiped
            // when update_option( QUEUE_OPTION, [] ) is written at the end of the run.
            $raw   = $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                self::QUEUE_OPTION
            ) );
            $queue = $raw ? maybe_unserialize( $raw ) : [];
            if ( ! is_array( $queue ) ) {
                $queue = [];
            }
            if ( empty( $queue ) ) {
                return;
            }

            $processed = 0;
            $remaining = [];
            // Track every job ID we read from the queue snapshot so we can detect
            // items added by concurrent requests (e.g. /upload-media) while we process.
            $original_ids = array_flip( array_column( $queue, 'job_id' ) );

            foreach ( $queue as $item ) {
                if ( $processed >= self::MAX_JOBS_PER_RUN ) {
                    $remaining[] = $item;
                    continue;
                }

                $job_id  = $item['job_id'];
                $type    = $item['type'];
                $sas_url = $item['sas_url'];

                // Load agent-provided hints stored when the job was queued.
                // DB fallback mirrors _update_job(): object cache may be closed in shutdown.
                $hints_key     = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
                $job_transient = get_transient( $hints_key );
                if ( false === $job_transient ) {
                    $db_val        = $wpdb->get_var( $wpdb->prepare(
                        "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                        '_transient_' . $hints_key
                    ) );
                    $job_transient = $db_val ? maybe_unserialize( $db_val ) : null;
                }
                $hints = ( is_array( $job_transient ) && isset( $job_transient['hints'] ) && is_array( $job_transient['hints'] ) )
                    ? $job_transient['hints']
                    : [];

                // Mark as processing
                error_log( '[KS Migration] process_queue: starting job=' . $job_id . ' type=' . $type );
                self::_update_job( $job_id, [ 'status' => 'processing', 'progress' => 5 ] );

                $success = false;
                try {
                    if ( 'db_export' === $type ) {
                        $success = self::_run_db_export( $job_id, $sas_url, $hints );
                    } elseif ( 'media_stream' === $type ) {
                        $container_base_url = $item['container_base_url'] ?? '';
                        $blob_prefix        = $item['blob_prefix'] ?? '';
                        $sas_token          = $item['sas_token'] ?? '';
                        $success = self::_run_media_stream( $job_id, $container_base_url, $blob_prefix, $sas_token, $hints );
                    } elseif ( 'media_upload' === $type ) {
                        // Legacy job type — kept for any jobs queued before Sprint M.
                        $success = self::_run_media_upload( $job_id, $sas_url, $hints );
                    } elseif ( 'content_export' === $type ) {
                        $source_path = $item['source_path'] ?? '';
                        $success = self::_run_content_export( $job_id, $sas_url, $source_path, $hints );
                    } elseif ( 'content_stream' === $type ) {
                        $container_base_url = $item['container_base_url'] ?? '';
                        $blob_prefix        = $item['blob_prefix'] ?? '';
                        $sas_token          = $item['sas_token'] ?? '';
                        $source_path        = $item['source_path'] ?? '';
                        $artifact           = $item['artifact'] ?? '';
                        $success = self::_run_content_stream( $job_id, $container_base_url, $blob_prefix, $sas_token, $source_path, $artifact, $hints );
                    }
                } catch ( Exception $e ) {
                    self::_update_job( $job_id, [
                        'status' => 'failed',
                        'error'  => substr( $e->getMessage(), 0, 500 ),
                    ] );
                    error_log( '[KS Migration] process_queue: job ' . $job_id . ' EXCEPTION: ' . $e->getMessage() );
                }

                if ( $success ) {
                    self::_update_job( $job_id, [ 'status' => 'complete', 'progress' => 100 ] );
                } elseif ( 'failed' !== self::_job_status( $job_id ) ) {
                    $remaining[] = $item; // Re-queue if not explicitly marked failed
                }

                $processed++;
            }

            // Re-read the queue directly from DB (bypassing per-process cache — same
            // reason as the initial read above) to pick up items enqueued by a concurrent
            // request while we were processing.  We add only items not in our original
            // snapshot AND not already done.
            $raw_fresh   = $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                self::QUEUE_OPTION
            ) );
            $fresh_queue = $raw_fresh ? maybe_unserialize( $raw_fresh ) : [];
            if ( ! is_array( $fresh_queue ) ) {
                $fresh_queue = [];
            }
            $new_items   = [];
            foreach ( $fresh_queue as $fresh_item ) {
                $fid = $fresh_item['job_id'] ?? '';
                if ( $fid && ! isset( $original_ids[ $fid ] ) ) {
                    $s = self::_job_status( $fid );
                    if ( 'complete' !== $s && 'failed' !== $s ) {
                        $new_items[] = $fresh_item;
                    }
                }
            }

            update_option( self::QUEUE_OPTION, array_values( array_merge( $remaining, $new_items ) ), false );
        } finally {
            $wpdb->delete( $wpdb->options, [ 'option_name' => $lock_name ] );
        }
    }

    /**
     * Drain the queue by running process_queue() back-to-back until the queue is
     * empty or the wall-clock budget is exhausted.
     *
     * process_queue() does ONE batch per job and returns, which — when invoked from
     * the background shutdown runner (set_time_limit(600) after fastcgi_finish_request)
     * — ends the long-lived background process after a single ~25 s batch and leaves
     * the rest of the work waiting for the next WP-Cron tick / server nudge (~60-90 s
     * apart). On a low-traffic source site that means large content streams crawl.
     *
     * Looping here keeps the SAME already-running background process busy for the full
     * window, so a big plugins/media export drains in minutes instead of hours. Each
     * inner batch still checkpoints, so a process killed early loses nothing.
     *
     * @param int $budget_seconds Stay safely under the runner's set_time_limit(600).
     */
    public static function drain_queue( int $budget_seconds = 550 ): void {
        $start = microtime( true );
        do {
            self::process_queue();

            // Read the queue straight from the DB (bypass per-process cache, same
            // reasoning as process_queue) to see whether incomplete work remains.
            global $wpdb;
            $raw      = $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                self::QUEUE_OPTION
            ) );
            $pending  = $raw ? maybe_unserialize( $raw ) : [];
            $has_work = is_array( $pending ) && ! empty( $pending );

            // Small pause between batches so we never hot-spin (e.g. if a job is
            // momentarily between checkpoints) and to be gentle on the source DB.
            if ( $has_work ) {
                usleep( 250000 ); // 0.25 s
            }
        } while ( $has_work && ( microtime( true ) - $start ) < $budget_seconds );
    }

    // ------------------------------------------------------------------
    // DB Export
    // ------------------------------------------------------------------

    /**
     * Export the WordPress database to a plain SQL dump and upload to Azure Blob.
     *
     * Streams mysqldump output to a temp file without gzip compression.
     * --single-transaction avoids table locks on InnoDB (zero impact on the live site).
     * --quick reads one row at a time, keeping memory usage minimal on shared hosting.
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool  true on success
     * @throws Exception  on mysqldump failure or upload failure
     */
    private static function _run_db_export( string $job_id, string $sas_url, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        $disable_fns    = array_filter( array_map( 'trim', explode( ',', (string) ini_get( 'disable_functions' ) ) ) );
        $exec_available = function_exists( 'exec' ) && ! in_array( 'exec', $disable_fns, true );

        $rate_limit_kbps = isset( $hints['stream_rate_limit_kbps'] ) ? max( 128, (int) $hints['stream_rate_limit_kbps'] ) : 0;

        $tmp_file = tempnam( sys_get_temp_dir(), 'ks_db_' ) . '.sql';

        try {
            if ( $exec_available ) {
                self::_mysqldump_export( $tmp_file, $rate_limit_kbps );
            } else {
                self::_wpdb_export( $job_id, $tmp_file );
            }

            self::_update_job( $job_id, [ 'progress' => 70 ] );
            self::_upload_file_to_blob( $sas_url, $tmp_file, 'application/octet-stream' );
            self::_update_job( $job_id, [ 'progress' => 100 ] );
            return true;

        } finally {
            if ( file_exists( $tmp_file ) ) {
                @unlink( $tmp_file );
            }
            putenv( 'MYSQL_PWD=' );
        }
    }

    /**
     * Export via mysqldump — used when exec() is available (default path).
     * --single-transaction: InnoDB snapshot, zero table locking.
     * --quick: reads one row at a time, minimal RAM on restricted accounts.
     */
    private static function _mysqldump_export( string $tmp_file, int $rate_limit_kbps = 0 ): void {
        $host     = escapeshellarg( DB_HOST );
        $user     = escapeshellarg( DB_USER );
        $database = escapeshellarg( DB_NAME );
        $tmp_esc  = escapeshellarg( $tmp_file );

        putenv( 'MYSQL_PWD=' . DB_PASSWORD );

        if ( $rate_limit_kbps > 0 ) {
            $pv_available = ! empty( shell_exec( 'which pv 2>/dev/null' ) );
            if ( $pv_available ) {
                $rate_arg = escapeshellarg( $rate_limit_kbps . 'k' );
                $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                     . "--quick --routines --triggers --add-drop-table {$database} "
                     . "| pv -q -L {$rate_arg} > {$tmp_esc} 2>/dev/null'";
            } else {
                $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                     . "--quick --routines --triggers --add-drop-table {$database} "
                     . "> {$tmp_esc} 2>/dev/null'";
            }
        } else {
            $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                 . "--quick --routines --triggers --add-drop-table {$database} "
                 . "> {$tmp_esc} 2>/dev/null'";
        }

        $output    = [];
        $exit_code = 0;
        exec( $cmd, $output, $exit_code );

        putenv( 'MYSQL_PWD=' );

        if ( 0 !== $exit_code ) {
            throw new Exception( 'mysqldump failed (exit=' . $exit_code . '): ' . implode( ' ', $output ) );
        }
        if ( ! file_exists( $tmp_file ) || 0 === filesize( $tmp_file ) ) {
            throw new Exception( 'mysqldump produced empty output.' );
        }
    }

    /**
     * PHP-native DB export fallback for environments where exec() is disabled
     * (e.g. WP Engine, Kinsta, some shared hosting).
     *
     * Iterates all tables via SHOW TABLES, writes DDL via SHOW CREATE TABLE, and
     * dumps rows as batched INSERT statements (500 rows/batch) to avoid PHP memory
     * exhaustion on large tables.
     *
     * Output is compatible with the mysqldump import path used by run_db_import.
     * Progress updates run from 5% to 65%, leaving 70% for upload completion.
     */
    private static function _wpdb_export( string $job_id, string $tmp_file ): void {
        global $wpdb;

        $fh = fopen( $tmp_file, 'wb' );
        if ( ! $fh ) {
            throw new Exception( 'PHP-native DB export: failed to open temp file for writing.' );
        }

        try {
            fwrite( $fh, "-- KloudStack PHP-native export (exec() unavailable)\n" );
            fwrite( $fh, "-- Generated: " . gmdate( 'Y-m-d H:i:s' ) . " UTC\n\n" );
            fwrite( $fh, "SET NAMES utf8mb4;\n" );
            fwrite( $fh, "SET FOREIGN_KEY_CHECKS=0;\n\n" );

            $tables = $wpdb->get_col( 'SHOW TABLES' );
            $total  = count( $tables );
            $done   = 0;

            foreach ( $tables as $table ) {
                $safe = '`' . str_replace( '`', '``', $table ) . '`';

                // DDL
                // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
                $create_row = $wpdb->get_row( "SHOW CREATE TABLE {$safe}", ARRAY_N );
                if ( $create_row ) {
                    fwrite( $fh, "DROP TABLE IF EXISTS {$safe};\n" );
                    fwrite( $fh, $create_row[1] . ";\n\n" );
                }

                // Row data — batched to avoid memory exhaustion on large tables
                $offset = 0;
                $batch  = 500;
                while ( true ) {
                    // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
                    $rows = $wpdb->get_results(
                        $wpdb->prepare( "SELECT * FROM {$safe} LIMIT %d OFFSET %d", $batch, $offset ),
                        ARRAY_A
                    );
                    if ( empty( $rows ) ) {
                        break;
                    }

                    $col_names = implode( ', ', array_map(
                        static fn( $c ) => '`' . str_replace( '`', '``', $c ) . '`',
                        array_keys( $rows[0] )
                    ) );

                    $value_rows = [];
                    foreach ( $rows as $row ) {
                        $vals = array_map( static function ( $v ) {
                            return is_null( $v ) ? 'NULL' : "'" . esc_sql( (string) $v ) . "'";
                        }, array_values( $row ) );
                        $value_rows[] = '(' . implode( ', ', $vals ) . ')';
                    }

                    fwrite( $fh, "INSERT INTO {$safe} ({$col_names}) VALUES\n" );
                    fwrite( $fh, implode( ",\n", $value_rows ) . ";\n" );

                    $offset += $batch;
                    if ( count( $rows ) < $batch ) {
                        break;
                    }
                }

                fwrite( $fh, "\n" );
                $done++;
                self::_update_job( $job_id, [ 'progress' => 5 + (int) ( 60 * $done / max( 1, $total ) ) ] );
            }

            fwrite( $fh, "SET FOREIGN_KEY_CHECKS=1;\n" );

        } finally {
            fclose( $fh );
        }

        if ( ! file_exists( $tmp_file ) || 0 === filesize( $tmp_file ) ) {
            throw new Exception( 'PHP-native DB export produced empty output.' );
        }
    }

    // ------------------------------------------------------------------
    // Media Stream — per-file direct Blob PUT (Sprint M)
    // ------------------------------------------------------------------

    /**
     * Stream every file in wp-content/uploads/ directly to Azure Blob Storage.
     *
     * Each file is PUT individually using a container-level SAS token — no ZIP,
     * no temp disk usage. The job transient tracks uploaded files so that a
     * retry/WP-Cron resumption skips already-completed files (checkpointing).
     *
     * A _manifest.json blob is uploaded as the final step to signal completion.
     *
     * @param string $job_id
     * @param string $container_base_url  e.g. https://{account}.blob.core.windows.net/kloudstack-migrations
     * @param string $blob_prefix         e.g. migrations/{id}/media/uploads
     * @param string $sas_token           Container-level write SAS (no leading '?')
     * @param array  $hints               Agent-provided hints (skip_extensions, max_file_size_mb)
     * @return bool  true when all files uploaded and manifest written
     * @throws Exception on unrecoverable upload failure
     */
    private static function _run_media_stream(
        string $job_id,
        string $container_base_url,
        string $blob_prefix,
        string $sas_token,
        array $hints = []
    ): bool {
        global $wpdb;
        error_log( '[KS Migration] _run_media_stream: START job=' . $job_id . ' container=' . $container_base_url . ' prefix=' . $blob_prefix . ' sas_len=' . strlen( $sas_token ) );

        // Validate the container base URL points to Azure Blob Storage over HTTPS.
        if ( 0 !== strpos( $container_base_url, 'https://' ) ) {
            throw new Exception( 'container_base_url must use HTTPS.' );
        }
        if ( false === strpos( parse_url( $container_base_url, PHP_URL_HOST ) ?? '', '.blob.core.windows.net' ) ) {
            throw new Exception( 'container_base_url host is not a trusted Azure Blob endpoint.' );
        }

        $uploads_dir = wp_upload_dir();
        $base_dir    = $uploads_dir['basedir'];

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Uploads directory not found: {$base_dir}" );
        }

        // Agent hints.
        $skip_extensions = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;

        // Batch size: number of files processed per WP-Cron tick.
        // Keeps each execution under ~8 minutes on slow shared hosting
        // (500 files × ~100 ms/HTTPS PUT = ~50 s, well within safe limits).
        $batch_size = 500;

        // Load checkpoint — list of relative paths already uploaded this job.
        //
        // v1.8.0 root-cause fix: the checkpoint must NOT use get_transient() at any point.
        //
        // With ext_object_cache=True (APCu/Redis), WordPress stores transients exclusively
        // in the external cache and never writes them to wp_options.  Two separate failure
        // modes combine to permanently stall the job at exactly one batch (20% for 2500 files):
        //
        // 1. SHUTDOWN CONTEXT (first batch, fired from /upload_media REST shutdown function):
        //    do_action('shutdown') closes APCu/Redis BEFORE our callback runs (PHP FIFO).
        //    get_transient() returns false. The v1.7.9 DB fallback reads _transient_ks_...
        //    from wp_options, but with ext_object_cache=True that row was never written by
        //    set_transient() — so the fallback also returns null. uploaded_files=[].
        //
        // 2. WP-CRON TICKS (subsequent batches, new PHP process, cache open):
        //    get_transient() succeeds — but returns the *original* job state from creation
        //    time (uploaded_files=[]).  The shutdown-context _update_job() calls only wrote
        //    to wp_options via DB-fallback; they never updated the external cache.  So every
        //    WP-Cron tick reads the stale cached state and re-uploads the same 500 files.
        //
        // Fix: store the uploaded-files checkpoint in a dedicated wp_options key
        // (ks_mig_ckpt_<job_id>) using $wpdb->replace() for writes and $wpdb->get_var()
        // for reads.  This bypasses the entire WordPress transient/cache stack and works
        // identically in both shutdown context and normal WP-Cron execution.
        $ckpt           = self::_read_media_checkpoint( $job_id );
        $uploaded       = $ckpt['uploaded_files'];
        $bytes_uploaded = $ckpt['bytes_uploaded'];
        $uploaded_set   = array_flip( $uploaded ); // O(1) lookups
        error_log( '[KS Migration] _run_media_stream: checkpoint loaded job=' . $job_id . ' already_uploaded=' . count( $uploaded ) . ' bytes_uploaded=' . $bytes_uploaded );

        // Build the full file list (only built once; subsequent batches use transient offset).
        $all_files = [];
        $iterator  = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
            RecursiveIteratorIterator::LEAVES_ONLY
        );
        foreach ( $iterator as $file ) {
            if ( ! $file->isFile() ) {
                continue;
            }
            if ( $skip_extensions ) {
                $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                    continue;
                }
            }
            if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                continue;
            }
            $all_files[] = [
                'abs'  => $file->getPathname(),
                'rel'  => str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() ),
                'size' => $file->getSize(),
            ];
        }

        $total_files = count( $all_files );
        $total_bytes = array_sum( array_column( $all_files, 'size' ) );

        error_log( '[KS Migration] _run_media_stream: enumerated total_files=' . $total_files . ' total_bytes=' . $total_bytes . ' base_dir=' . $base_dir );

        if ( 0 === $total_files ) {
            error_log( '[KS Migration] _run_media_stream: no files found — marking complete immediately' );
        }

        // Update totals in transient so the polling loop can display accurate counts.
        self::_update_job( $job_id, [
            'total_files'  => $total_files,
            'total_bytes'  => $total_bytes,
        ] );

        $files_this_batch    = 0;
        // How often to persist the uploaded_files checkpoint. Progress (count/bytes) is
        // written after every file (lightweight); the full path list is expensive to
        // serialise so we batch it every N files to avoid O(N²) write traffic.
        $checkpoint_interval = 50;

        // Wall-clock guard: yield before the host's PHP max_execution_time so a
        // large library is never killed mid-batch before a checkpoint is written
        // (count-based batching alone can blow the time limit on slow uploads).
        $max_exec    = (int) ini_get( 'max_execution_time' );
        // Cap each batch at ~25 s so we checkpoint frequently and yield well before
        // any host execution limit. The background runner calls set_time_limit(600),
        // which makes max_execution_time report 600 even on hosts that won't actually
        // honour it — so an uncapped 0.8×600 budget would risk a mid-batch kill before
        // a checkpoint. drain_queue() loops these short batches back-to-back to use the
        // full background window.
        $time_budget = $max_exec > 0 ? max( 10, min( 25, (int) floor( $max_exec * 0.8 ) ) ) : 25;
        $start_time  = microtime( true );

        foreach ( $all_files as $entry ) {
            $rel_path = $entry['rel'];

            // Skip files already uploaded (checkpointing — safe to resume after PHP-FPM kill).
            if ( isset( $uploaded_set[ $rel_path ] ) ) {
                continue;
            }

            // Normalise path separators to forward-slash for the blob name.
            $blob_rel  = str_replace( DIRECTORY_SEPARATOR, '/', $rel_path );
            $blob_name = "{$blob_prefix}/{$blob_rel}";
            // URL-encode each path segment (preserve '/') so files with spaces or
            // special characters (e.g. brackets in PhpSpreadsheet fixtures such as
            // "[Content_Types].xml") produce a valid URL. cURL otherwise rejects the
            // unencoded illegal characters with "URL using bad/illegal format or
            // missing URL" and the whole content/media job fails. The blob is still
            // stored under its real (decoded) name — Azure decodes the URL path.
            $blob_path = implode( '/', array_map( 'rawurlencode', explode( '/', $blob_name ) ) );
            $blob_url  = "{$container_base_url}/{$blob_path}?{$sas_token}";

            // Detect MIME type for accurate Content-Type header.
            $mime_type = 'application/octet-stream';
            if ( function_exists( 'mime_content_type' ) ) {
                $detected = mime_content_type( $entry['abs'] );
                if ( $detected ) {
                    $mime_type = $detected;
                }
            }

            if ( 1 === $files_this_batch + 1 ) {
                error_log( '[KS Migration] _run_media_stream: uploading first file=' . $blob_rel . ' size=' . $entry['size'] );
            }
            self::_upload_blob_put( $blob_url, $entry['abs'], $mime_type );

            // Record as uploaded in checkpoint.
            $uploaded[]              = $rel_path;
            $uploaded_set[$rel_path] = true;
            $bytes_uploaded         += $entry['size'];
            $files_this_batch++;

            // Lightweight progress update after every file — no large arrays.
            // min(99) reserves 100% for the final manifest signal.
            // max(1) ensures progress is always > 0% once we've uploaded at least one file
            // so the Django stagnation timer never fires prematurely on large libraries.
            $progress = $total_files > 0
                ? max( 1, min( 99, (int) ( count( $uploaded ) / $total_files * 99 ) ) )
                : 99;
            self::_update_job( $job_id, [
                'progress'       => $progress,
                'files_uploaded' => count( $uploaded ),
                'bytes_uploaded' => $bytes_uploaded,
            ] );

            // Heavy checkpoint (uploaded_files path list) every N files so re-runs skip
            // already-uploaded files without writing a growing blob on every single PUT.
            // Written directly to wp_options (bypasses cache) — see _write_media_checkpoint().
            if ( 0 === $files_this_batch % $checkpoint_interval ) {
                self::_write_media_checkpoint( $job_id, $uploaded, $bytes_uploaded );
            }

            // Yield after the batch limit OR the time budget to allow WP-Cron to reschedule.
            if ( $files_this_batch >= $batch_size
                || ( microtime( true ) - $start_time ) >= $time_budget ) {
                // Flush the final checkpoint directly to wp_options before exiting so the
                // next cron tick resumes from where we stopped (bypasses external cache).
                self::_write_media_checkpoint( $job_id, $uploaded, $bytes_uploaded );
                self::_update_job( $job_id, [ 'status' => 'processing' ] );
                return false; // Returning false re-queues the item for the next cron tick.
            }
        }

        // All files uploaded — write _manifest.json as the completion signal.
        $manifest = json_encode( [
            'total_files'  => $total_files,
            'total_bytes'  => $total_bytes,
            'completed_at' => time(),
        ] );
        // Build the manifest blob URL — strip /uploads suffix from the prefix so
        // the manifest lands at the container root for that migration, not inside /uploads.
        $media_base   = preg_replace( '#/uploads$#', '', $blob_prefix );
        $manifest_url = "{$container_base_url}/{$media_base}/_manifest.json?{$sas_token}";

        $tmp_manifest = tempnam( sys_get_temp_dir(), 'ks_manifest_' ) . '.json';
        try {
            file_put_contents( $tmp_manifest, $manifest );
            self::_upload_blob_put( $manifest_url, $tmp_manifest, 'application/json' );
        } finally {
            if ( file_exists( $tmp_manifest ) ) {
                unlink( $tmp_manifest );
            }
        }

        self::_update_job( $job_id, [
            'progress'       => 100,
            'files_uploaded' => $total_files,
            'bytes_uploaded' => $total_bytes,
        ] );

        // Clean up the dedicated checkpoint row — job is complete.
        self::_delete_media_checkpoint( $job_id );

        return true;
    }

    // ------------------------------------------------------------------
    // Media Upload — legacy ZIP approach (kept for backward compat)
    // ------------------------------------------------------------------

    /**
     * Create a ZIP of wp-content/uploads and upload to Azure Blob.
     * Kept for any jobs queued before Sprint M. New jobs use _run_media_stream().
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool
     * @throws Exception
     */
    private static function _run_media_upload( string $job_id, string $sas_url, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        if ( ! class_exists( 'ZipArchive' ) ) {
            throw new Exception( 'PHP ZipArchive extension is not available.' );
        }

        $uploads_dir = wp_upload_dir();
        $base_dir    = $uploads_dir['basedir'];

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Uploads directory not found: {$base_dir}" );
        }

        // Agent hints: skip files by extension or size on retry attempts.
        // These are applied when a previous attempt timed out due to large video/archive files.
        $skip_extensions   = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;  // 0 = no limit

        $tmp_zip = tempnam( sys_get_temp_dir(), 'ks_media_' ) . '.zip';

        try {
            $zip = new ZipArchive();
            if ( true !== $zip->open( $tmp_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
                throw new Exception( "Cannot create ZIP archive at {$tmp_zip}" );
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
                RecursiveIteratorIterator::LEAVES_ONLY
            );

            $file_count = 0;
            foreach ( $iterator as $file ) {
                if ( $file->isFile() ) {
                    // Apply agent hints: skip by extension and/or file size.
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }

                    $relative_path = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() );
                    $zip->addFile( $file->getPathname(), $relative_path );
                    $file_count++;

                    // Update progress periodically during the zip phase (5–55%).
                    // ZipArchive::addFile() only stores the path reference — actual
                    // file data is compressed at close() time, so no memory flush
                    // is needed here.
                    if ( 0 === $file_count % 100 ) {
                        self::_update_job( $job_id, [ 'progress' => min( 55, 5 + (int) ( $file_count / 20 ) ) ] );
                    }
                }
            }

            $zip->close();

            if ( ! file_exists( $tmp_zip ) || 0 === filesize( $tmp_zip ) ) {
                throw new Exception( 'ZIP archive creation produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 65 ] );

            // Upload to Azure Blob via SAS PUT
            self::_upload_file_to_blob( $sas_url, $tmp_zip, 'application/zip' );

            return true;

        } finally {
            if ( file_exists( $tmp_zip ) ) {
                unlink( $tmp_zip );
            }
        }
    }

    // ------------------------------------------------------------------
    // Content export helper (plugins / themes / media / mu-plugins / custom-root)
    // ------------------------------------------------------------------

    /**
     * ZIP the given source directory and upload to Azure Blob via SAS URL.
     *
     * Special value 'custom-root': exports only root-level files from WP_CONTENT_DIR,
     * excluding standard sub-directories (plugins, themes, uploads, mu-plugins,
     * languages, upgrade).
     *
     * @param string $job_id      Job transient key
     * @param string $sas_url     Azure Blob SAS PUT URL
     * @param string $source_path Absolute path, or 'custom-root' sentinel
     * @param array  $hints       Optional skip_extensions / max_file_size_mb
     * @throws Exception on filesystem or upload failure
     */
    private static function _run_content_export( string $job_id, string $sas_url, string $source_path, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        if ( ! class_exists( 'ZipArchive' ) ) {
            throw new Exception( 'PHP ZipArchive extension is not available.' );
        }

        $skip_extensions = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes  = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;

        $is_custom_root = ( 'custom-root' === $source_path );
        $base_dir       = $is_custom_root ? WP_CONTENT_DIR : $source_path;

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Source directory does not exist: {$base_dir}" );
        }

        // Sub-directories to exclude when scanning WP_CONTENT_DIR root.
        $excluded_subdirs = [ 'plugins', 'themes', 'uploads', 'mu-plugins', 'languages', 'upgrade' ];

        // WordPress drop-in files are environment-specific: they contain connection
        // credentials, paths, and configuration for the SOURCE server.  Copying them
        // to the target stack causes PHP fatal errors (e.g. W3TC's db.php calling
        // wp_get_wp_version() before WordPress has finished bootstrapping).
        // Exclude them here — caching plugins will regenerate correct drop-ins for
        // the target environment when they are re-enabled after migration.
        $excluded_root_files = [
            'db.php',
            'advanced-cache.php',
            'object-cache.php',
            'db-error.php',
            'maintenance.php',
        ];

        $tmp_zip = tempnam( sys_get_temp_dir(), 'ks_content_' ) . '.zip';

        try {
            $zip = new ZipArchive();
            if ( true !== $zip->open( $tmp_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
                throw new Exception( "Cannot create ZIP archive at {$tmp_zip}" );
            }

            $file_count = 0;

            if ( $is_custom_root ) {
                // Only root-level files in WP_CONTENT_DIR; skip standard sub-directories.
                $dir_iter = new DirectoryIterator( $base_dir );
                foreach ( $dir_iter as $file ) {
                    if ( $file->isDot() ) {
                        continue;
                    }
                    if ( $file->isDir() ) {
                        if ( in_array( $file->getFilename(), $excluded_subdirs, true ) ) {
                            continue;
                        }
                        // Non-standard sub-directory: include recursively.
                        $sub_iter = new RecursiveIteratorIterator(
                            new RecursiveDirectoryIterator( $file->getPathname(), FilesystemIterator::SKIP_DOTS ),
                            RecursiveIteratorIterator::LEAVES_ONLY
                        );
                        foreach ( $sub_iter as $sub_file ) {
                            if ( ! $sub_file->isFile() ) {
                                continue;
                            }
                            if ( $skip_extensions ) {
                                $ext = strtolower( pathinfo( $sub_file->getFilename(), PATHINFO_EXTENSION ) );
                                if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                                    continue;
                                }
                            }
                            if ( $max_size_bytes > 0 && $sub_file->getSize() > $max_size_bytes ) {
                                continue;
                            }
                            $relative = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $sub_file->getPathname() );
                            $zip->addFile( $sub_file->getPathname(), $relative );
                            $file_count++;
                        }
                        continue;
                    }
                    // Root-level file.
                    if ( in_array( $file->getFilename(), $excluded_root_files, true ) ) {
                        continue;
                    }
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }
                    $zip->addFile( $file->getPathname(), $file->getFilename() );
                    $file_count++;
                }
            } else {
                $iterator = new RecursiveIteratorIterator(
                    new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
                    RecursiveIteratorIterator::LEAVES_ONLY
                );
                foreach ( $iterator as $file ) {
                    if ( ! $file->isFile() ) {
                        continue;
                    }
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }
                    $relative = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() );
                    $zip->addFile( $file->getPathname(), $relative );
                    $file_count++;
                    if ( 0 === $file_count % 100 ) {
                        self::_update_job( $job_id, [ 'progress' => min( 55, 5 + (int) ( $file_count / 20 ) ) ] );
                    }
                }
            }

            $zip->close();

            if ( ! file_exists( $tmp_zip ) || 0 === filesize( $tmp_zip ) ) {
                throw new Exception( 'ZIP archive creation produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 65 ] );
            self::_upload_file_to_blob( $sas_url, $tmp_zip, 'application/zip' );

            return true;

        } finally {
            if ( file_exists( $tmp_zip ) ) {
                unlink( $tmp_zip );
            }
        }
    }

    // ------------------------------------------------------------------
    // Content streaming (per-file, checkpointed — v1.9.0)
    // ------------------------------------------------------------------

    /**
     * Stream every file in a wp-content sub-directory to Azure Blob Storage.
     *
     * Per-file PUT with checkpoint — mirrors _run_media_stream() for the plugins,
     * themes, and mu-plugins directories.  Eliminates the single-pass ZIP bottleneck
     * that caused PHP timeout stalls on GoDaddy and other hosts with strict wall-clock
     * limits on background PHP processes.
     *
     * Batch size: 200 files per WP-Cron tick (content files tend to be larger than
     * media thumbnails, keeping each batch safely under GoDaddy's timeout).
     *
     * Checkpoint reuse: _read_media_checkpoint / _write_media_checkpoint /
     * _delete_media_checkpoint use ks_mig_ckpt_<job_id> — unique per job, so content
     * stream jobs reuse the same raw-mysqli checkpoint machinery without conflict.
     *
     * @param string $job_id
     * @param string $container_base_url  Azure Blob container URL (HTTPS)
     * @param string $blob_prefix         Blob path prefix, e.g. migrations/{id}/content/plugins
     * @param string $sas_token           Container-level write SAS (no leading ?)
     * @param string $source_path         Absolute filesystem path to the source directory
     * @param string $artifact            Artifact name for logging ('plugins', 'themes', 'mu-plugins')
     * @param array  $hints               Agent hints (skip_extensions, max_file_size_mb)
     * @return bool true when complete, false to re-queue for next tick
     * @throws Exception on unrecoverable failure
     */
    private static function _run_content_stream(
        string $job_id,
        string $container_base_url,
        string $blob_prefix,
        string $sas_token,
        string $source_path,
        string $artifact,
        array $hints = []
    ): bool {
        error_log( '[KS Migration] _run_content_stream: START job=' . $job_id . ' artifact=' . $artifact . ' source=' . $source_path . ' prefix=' . $blob_prefix );

        if ( 0 !== strpos( $container_base_url, 'https://' ) ) {
            throw new Exception( 'container_base_url must use HTTPS.' );
        }
        if ( false === strpos( parse_url( $container_base_url, PHP_URL_HOST ) ?? '', '.blob.core.windows.net' ) ) {
            throw new Exception( 'container_base_url host is not a trusted Azure Blob endpoint.' );
        }

        if ( ! is_dir( $source_path ) ) {
            throw new Exception( "Source directory does not exist: {$source_path}" );
        }

        $skip_extensions = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes  = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;

        // WordPress drop-in files are environment-specific (credentials, paths for the
        // source server).  These shouldn't appear inside plugins/ or themes/ but we
        // exclude them defensively to avoid PHP fatal errors on the target environment.
        $excluded_filenames = [ 'db.php', 'advanced-cache.php', 'object-cache.php', 'db-error.php', 'maintenance.php' ];

        // 200 files per tick — smaller than media (500) because plugin PHP/JS/CSS files
        // average larger than image thumbnails, keeping each batch under safe limits on
        // restricted hosts like GoDaddy.
        $batch_size = 200;

        // Load checkpoint — list of relative paths already uploaded this job.
        // Reuses _read_media_checkpoint() / _write_media_checkpoint() since the checkpoint
        // key (ks_mig_ckpt_<job_id>) is unique per job regardless of job type.
        $ckpt           = self::_read_media_checkpoint( $job_id );
        $uploaded       = $ckpt['uploaded_files'];
        $bytes_uploaded = $ckpt['bytes_uploaded'];
        $uploaded_set   = array_flip( $uploaded );
        error_log( '[KS Migration] _run_content_stream: checkpoint loaded job=' . $job_id . ' already_uploaded=' . count( $uploaded ) . ' bytes=' . $bytes_uploaded );

        // Enumerate all files recursively in $source_path.
        $all_files = [];
        $iterator  = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator( $source_path, FilesystemIterator::SKIP_DOTS ),
            RecursiveIteratorIterator::LEAVES_ONLY
        );
        foreach ( $iterator as $file ) {
            if ( ! $file->isFile() ) {
                continue;
            }
            if ( in_array( $file->getFilename(), $excluded_filenames, true ) ) {
                continue;
            }
            if ( $skip_extensions ) {
                $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                    continue;
                }
            }
            if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                continue;
            }
            $all_files[] = [
                'abs'  => $file->getPathname(),
                'rel'  => str_replace( $source_path . DIRECTORY_SEPARATOR, '', $file->getPathname() ),
                'size' => $file->getSize(),
            ];
        }

        $total_files = count( $all_files );
        $total_bytes = array_sum( array_column( $all_files, 'size' ) );

        error_log( '[KS Migration] _run_content_stream: enumerated total_files=' . $total_files . ' total_bytes=' . $total_bytes . ' artifact=' . $artifact );

        if ( 0 === $total_files ) {
            error_log( '[KS Migration] _run_content_stream: no files found — marking complete immediately' );
        }

        self::_update_job( $job_id, [
            'total_files' => $total_files,
            'total_bytes' => $total_bytes,
        ] );

        $files_this_batch    = 0;
        $checkpoint_interval = 50;

        // Wall-clock guard: yield (checkpoint + return) before the host's PHP
        // max_execution_time. Count-based batching alone is not safe — a heavy
        // plugin (e.g. wpdatatables/PhpSpreadsheet: hundreds of per-file PUTs)
        // can exceed the time limit mid-batch and be killed BEFORE a checkpoint
        // is written, leaving the job to resume from the same point forever
        // (the indefinite export_media stall). Yielding on time guarantees each
        // cron tick persists durable progress.
        $max_exec    = (int) ini_get( 'max_execution_time' );
        // Cap each batch at ~25 s so we checkpoint frequently and yield well before
        // any host execution limit. The background runner calls set_time_limit(600),
        // which makes max_execution_time report 600 even on hosts that won't actually
        // honour it — so an uncapped 0.8×600 budget would risk a mid-batch kill before
        // a checkpoint. drain_queue() loops these short batches back-to-back to use the
        // full background window.
        $time_budget = $max_exec > 0 ? max( 10, min( 25, (int) floor( $max_exec * 0.8 ) ) ) : 25;
        $start_time  = microtime( true );

        foreach ( $all_files as $entry ) {
            $rel_path = $entry['rel'];

            if ( isset( $uploaded_set[ $rel_path ] ) ) {
                continue;
            }

            // Normalise to forward-slash for the blob name.
            $blob_rel  = str_replace( DIRECTORY_SEPARATOR, '/', $rel_path );
            $blob_name = "{$blob_prefix}/{$blob_rel}";
            // URL-encode each path segment (preserve '/') so files with spaces or
            // special characters (e.g. brackets in PhpSpreadsheet fixtures such as
            // "[Content_Types].xml") produce a valid URL. cURL otherwise rejects the
            // unencoded illegal characters with "URL using bad/illegal format or
            // missing URL" and the whole content/media job fails. The blob is still
            // stored under its real (decoded) name — Azure decodes the URL path.
            $blob_path = implode( '/', array_map( 'rawurlencode', explode( '/', $blob_name ) ) );
            $blob_url  = "{$container_base_url}/{$blob_path}?{$sas_token}";

            $mime_type = 'application/octet-stream';
            if ( function_exists( 'mime_content_type' ) ) {
                $detected = mime_content_type( $entry['abs'] );
                if ( $detected ) {
                    $mime_type = $detected;
                }
            }

            if ( 1 === $files_this_batch + 1 ) {
                error_log( '[KS Migration] _run_content_stream: uploading first file=' . $blob_rel . ' size=' . $entry['size'] );
            }
            self::_upload_blob_put( $blob_url, $entry['abs'], $mime_type );

            $uploaded[]              = $rel_path;
            $uploaded_set[$rel_path] = true;
            $bytes_uploaded         += $entry['size'];
            $files_this_batch++;

            $progress = $total_files > 0
                ? max( 1, min( 99, (int) ( count( $uploaded ) / $total_files * 99 ) ) )
                : 99;
            self::_update_job( $job_id, [
                'progress'       => $progress,
                'files_uploaded' => count( $uploaded ),
                'bytes_uploaded' => $bytes_uploaded,
                'message'        => $blob_rel,
            ] );

            if ( 0 === $files_this_batch % $checkpoint_interval ) {
                self::_write_media_checkpoint( $job_id, $uploaded, $bytes_uploaded );
            }

            if ( $files_this_batch >= $batch_size
                || ( microtime( true ) - $start_time ) >= $time_budget ) {
                self::_write_media_checkpoint( $job_id, $uploaded, $bytes_uploaded );
                self::_update_job( $job_id, [ 'status' => 'processing' ] );
                return false;
            }
        }

        // All files uploaded — write _manifest.json as the completion signal.
        // Unlike media (which strips /uploads), the manifest lands directly at
        // {blob_prefix}/_manifest.json so get_content_manifest() on the server
        // can check migrations/{id}/content/{artifact}/_manifest.json.
        $manifest = json_encode( [
            'artifact'     => $artifact,
            'total_files'  => $total_files,
            'total_bytes'  => $total_bytes,
            'completed_at' => time(),
        ] );
        $manifest_url = "{$container_base_url}/{$blob_prefix}/_manifest.json?{$sas_token}";

        $tmp_manifest = tempnam( sys_get_temp_dir(), 'ks_manifest_' ) . '.json';
        try {
            file_put_contents( $tmp_manifest, $manifest );
            self::_upload_blob_put( $manifest_url, $tmp_manifest, 'application/json' );
        } finally {
            if ( file_exists( $tmp_manifest ) ) {
                unlink( $tmp_manifest );
            }
        }

        self::_update_job( $job_id, [
            'progress'       => 100,
            'files_uploaded' => $total_files,
            'bytes_uploaded' => $total_bytes,
        ] );

        self::_delete_media_checkpoint( $job_id );

        return true;
    }

    // ------------------------------------------------------------------
    // Azure Blob upload helpers
    // ------------------------------------------------------------------

    /**
     * Upload a local file to an Azure Blob using a SAS PUT URL.
     *
     * Includes x-ms-version (unlocks 5 GB single PUT), x-ms-blob-content-md5
     * (Azure verifies integrity on ingest), and accurate Content-Type per file.
     * Uses cURL streaming PUT to avoid loading the file into PHP memory.
     *
     * @param string $sas_url    Full blob SAS URL (must be HTTPS)
     * @param string $local_path Full filesystem path to the file
     * @param string $mime_type  MIME type for Content-Type header
     * @throws Exception on upload failure
     */
    /**
     * Phase-1 (server-side migration) thin upload primitive.
     *
     * PUT a single local file to a worker-supplied blob URL and return a result array.
     * Unlike the queue/drain-loop path, this does NO batching, pacing, checkpointing or
     * URL-construction — the KloudStack worker owns all of that (it builds the encoded
     * blob URL, drives concurrency, and retries). This is just "given a local file and a
     * destination URL, PUT it." See server/docs/SERVER_SIDE_MIGRATION_DESIGN.md.
     *
     * @return array{ok:bool, bytes?:int, error?:string}
     */
    public static function upload_single_file( string $local_path, string $blob_url ): array {
        if ( ! is_file( $local_path ) ) {
            return [ 'ok' => false, 'error' => 'file not found' ];
        }
        $mime = 'application/octet-stream';
        if ( function_exists( 'mime_content_type' ) ) {
            $detected = @mime_content_type( $local_path );
            if ( $detected ) {
                $mime = $detected;
            }
        }
        try {
            self::_upload_blob_put( $blob_url, $local_path, $mime );
            return [ 'ok' => true, 'bytes' => (int) filesize( $local_path ) ];
        } catch ( Exception $e ) {
            return [ 'ok' => false, 'error' => substr( $e->getMessage(), 0, 300 ) ];
        }
    }

    private static function _upload_blob_put( string $sas_url, string $local_path, string $mime_type ): void {
        $file_size = filesize( $local_path );
        $fh        = fopen( $local_path, 'rb' );

        if ( false === $fh ) {
            throw new Exception( "Cannot open file for upload: {$local_path}" );
        }

        try {
            // Compute MD5 for server-side integrity verification.
            // Azure rejects the PUT with HTTP 400 if the hash doesn't match.
            $md5_b64 = base64_encode( hash_file( 'md5', $local_path, true ) );

            $ch = curl_init( $sas_url );
            curl_setopt_array( $ch, [
                CURLOPT_PUT            => true,
                CURLOPT_INFILE         => $fh,
                CURLOPT_INFILESIZE     => $file_size,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => 3600,
                CURLOPT_HTTPHEADER     => [
                    'Content-Type: ' . $mime_type,
                    'x-ms-blob-type: BlockBlob',
                    'x-ms-version: 2021-06-08',     // unlocks 5 GB single PUT limit
                    'x-ms-blob-content-md5: ' . $md5_b64,
                    'Expect:',                       // suppress 100-Continue delay with Azure
                ],
            ] );

            $body      = curl_exec( $ch );
            $http_code = (int) curl_getinfo( $ch, CURLINFO_HTTP_CODE );
            $curl_err  = curl_error( $ch );
            curl_close( $ch );

            if ( $curl_err ) {
                throw new Exception( 'cURL upload error: ' . $curl_err );
            }

            if ( $http_code < 200 || $http_code >= 300 ) {
                throw new Exception( "Azure Blob upload failed (HTTP {$http_code}): " . substr( (string) $body, 0, 300 ) );
            }
        } finally {
            fclose( $fh );
        }
    }

    /**
     * Backward-compat wrapper used by _run_db_export and _run_content_export.
     * Delegates to _upload_blob_put — kept so callers don't need updating.
     */
    private static function _upload_file_to_blob( string $sas_url, string $local_path, string $mime_type ): void {
        self::_upload_blob_put( $sas_url, $local_path, $mime_type );
    }

    // ------------------------------------------------------------------
    // Job helpers
    // ------------------------------------------------------------------

    private static function _update_job( string $job_id, array $updates ): void {
        global $wpdb;
        $transient_key  = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $option_name    = '_transient_' . $transient_key;

        // Primary path: normal transient read/write (works outside shutdown context).
        $job = get_transient( $transient_key );

        if ( false === $job ) {
            // Fallback for post-fastcgi_finish_request shutdown context: WordPress's own
            // shutdown function fires do_action('shutdown') — which closes the object cache
            // (W3TC, APCu, Redis) — BEFORE our shutdown function runs (PHP FIFO order).
            // Also fires when another PHP-FPM worker created the transient via a
            // process-local cache (APCu), making it invisible to this worker's get_transient().
            // RestEndpoints::_shadow_write_transient() guarantees the row exists in wp_options.
            $db_val = $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                $option_name
            ) );
            if ( null === $db_val ) {
                error_log( '[KS Migration] _update_job DB-fallback: ROW MISSING for ' . $job_id . ' (option=' . $option_name . ') wpdb_err=' . $wpdb->last_error );
                return; // Genuinely missing — nothing to update.
            }
            $job = maybe_unserialize( $db_val );
            if ( ! is_array( $job ) ) {
                error_log( '[KS Migration] _update_job DB-fallback: unserialize failed for ' . $job_id );
                return;
            }
            $job = array_merge( $job, $updates );
            // Use REPLACE (INSERT OR UPDATE) instead of UPDATE so the write succeeds even
            // when the MySQL user lacks UPDATE privilege — observed on some managed hosts
            // where db_write_roundtrip (which uses replace) passes but update returns 0.
            $rows = $wpdb->replace(
                $wpdb->options,
                [
                    'option_name'  => $option_name,
                    'option_value' => maybe_serialize( $job ),
                    'autoload'     => 'no',
                ]
            );
            error_log( '[KS Migration] _update_job DB-fallback: ' . $job_id . ' rows_affected=' . $rows . ' progress=' . ( $updates['progress'] ?? '?' ) . ' status=' . ( $updates['status'] ?? '?' ) . ' wpdb_err=' . $wpdb->last_error );
            // Write audit entry accessible via /job-debug so we can see the DB write
            // result remotely without needing access to the WordPress debug.log file.
            $wpdb->replace( $wpdb->options, [
                'option_name'  => 'ks_mig_audit_' . substr( $job_id, -12 ),
                'option_value' => json_encode( [
                    'job_id'  => $job_id,
                    'path'    => 'db_fallback',
                    'updates' => $updates,
                    'rows'    => $rows,
                    'err'     => $wpdb->last_error ?: null,
                    'ts'      => time(),
                ] ),
                'autoload'     => 'no',
            ] );
            // Bust any stale in-memory option cache so the next get_transient() / get_option()
            // reads the fresh DB value rather than a cached 0% snapshot.
            wp_cache_delete( $option_name, 'options' );
            return;
        }

        $job = array_merge( $job, $updates );
        set_transient( $transient_key, $job, KloudStack_Migration_RestEndpoints::JOB_TTL );
        // Mirror into wp_options using REPLACE so the write succeeds even when the MySQL
        // user lacks UPDATE privilege (same fix as the DB-fallback path above).
        $wpdb->replace(
            $wpdb->options,
            [
                'option_name'  => $option_name,
                'option_value' => maybe_serialize( $job ),
                'autoload'     => 'no',
            ]
        );
        // Audit entry for primary path too (helps distinguish which path ran in logs).
        $wpdb->replace( $wpdb->options, [
            'option_name'  => 'ks_mig_audit_' . substr( $job_id, -12 ),
            'option_value' => json_encode( [
                'job_id'  => $job_id,
                'path'    => 'primary',
                'updates' => $updates,
                'ts'      => time(),
            ] ),
            'autoload'     => 'no',
        ] );
    }

    private static function _job_status( string $job_id ): string {
        global $wpdb;
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job           = get_transient( $transient_key );
        if ( false === $job ) {
            // Same shutdown-context fallback as _update_job.
            $db_val = $wpdb->get_var( $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
                '_transient_' . $transient_key
            ) );
            if ( null === $db_val ) {
                return 'unknown';
            }
            $job = maybe_unserialize( $db_val );
        }
        return is_array( $job ) ? ( $job['status'] ?? 'unknown' ) : 'unknown';
    }

    // ------------------------------------------------------------------
    // Media checkpoint helpers — direct wp_options read/write, no cache
    // ------------------------------------------------------------------

    /**
     * Return the wp_options key used to store the media upload checkpoint.
     * Kept short to stay well under the 191-byte index limit on option_name.
     */
    private static function _ckpt_option_key( string $job_id ): string {
        return 'ks_mig_ckpt_' . $job_id;
    }

    /**
     * Read the media upload checkpoint using a raw mysqli query, bypassing both the
     * WordPress object cache AND W3TC's database cache hooks entirely.
     *
     * Root cause of the v1.8.0/v1.8.1 stall: W3TC database cache (backed by APCu when
     * Redis is unavailable) caches the initial NULL result for the ks_mig_ckpt_ SELECT.
     * When $wpdb->replace() writes the checkpoint, W3TC should invalidate the APCu cache
     * entry, but the invalidation silently fails when Redis is unreachable.  Every
     * subsequent $wpdb->get_var() call then hits the stale NULL cache, returning [] for
     * uploaded_files so each batch re-uploads the same 500 files.  Using raw mysqli_query
     * on $wpdb->dbh bypasses $wpdb->query() entirely, removing all WordPress/W3TC hooks.
     *
     * @return array{ uploaded_files: string[], bytes_uploaded: int }
     */
    private static function _read_media_checkpoint( string $job_id ): array {
        global $wpdb;
        $key    = self::_ckpt_option_key( $job_id );
        $sql    = $wpdb->prepare(
            "SELECT option_value FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
            $key
        );
        $result = mysqli_query( $wpdb->dbh, $sql );
        $raw    = false;
        if ( $result ) {
            $row = mysqli_fetch_row( $result );
            $raw = $row ? $row[0] : false;
            mysqli_free_result( $result );
        }
        if ( ! $raw ) {
            $mysqli_err = mysqli_error( $wpdb->dbh ) ?: 'none';
            error_log( '[KS Migration] _read_media_checkpoint: NO ROW job=' . $job_id . ' key=' . $key . ' mysqli_err=' . $mysqli_err );
            return [ 'uploaded_files' => [], 'bytes_uploaded' => 0 ];
        }
        $data = maybe_unserialize( $raw );
        if ( ! is_array( $data ) ) {
            error_log( '[KS Migration] _read_media_checkpoint: UNSERIALIZE FAILED job=' . $job_id . ' raw_len=' . strlen( $raw ) );
            return [ 'uploaded_files' => [], 'bytes_uploaded' => 0 ];
        }
        $files_count = isset( $data['uploaded_files'] ) && is_array( $data['uploaded_files'] ) ? count( $data['uploaded_files'] ) : 0;
        error_log( '[KS Migration] _read_media_checkpoint: OK job=' . $job_id . ' files=' . $files_count . ' bytes=' . ( $data['bytes_uploaded'] ?? 0 ) );
        return [
            'uploaded_files' => is_array( $data['uploaded_files'] ?? null ) ? $data['uploaded_files'] : [],
            'bytes_uploaded' => (int) ( $data['bytes_uploaded'] ?? 0 ),
        ];
    }

    /**
     * Persist the media upload checkpoint using a raw mysqli query, bypassing both the
     * WordPress object cache AND W3TC's database cache hooks (same reason as _read).
     */
    private static function _write_media_checkpoint( string $job_id, array $uploaded, int $bytes_uploaded ): void {
        global $wpdb;
        $key   = self::_ckpt_option_key( $job_id );
        $value = maybe_serialize( [
            'uploaded_files' => $uploaded,
            'bytes_uploaded' => $bytes_uploaded,
        ] );
        $sql   = $wpdb->prepare(
            "INSERT INTO {$wpdb->options} (option_name, option_value, autoload) VALUES (%s, %s, 'no') ON DUPLICATE KEY UPDATE option_value = VALUES(option_value), autoload = 'no'",
            $key,
            $value
        );
        $ok    = (bool) mysqli_query( $wpdb->dbh, $sql );
        $rows  = $ok ? (int) mysqli_affected_rows( $wpdb->dbh ) : 0;
        $err   = $ok ? 'none' : ( mysqli_error( $wpdb->dbh ) ?: 'unknown' );
        error_log( '[KS Migration] _write_media_checkpoint: job=' . $job_id . ' files=' . count( $uploaded ) . ' bytes=' . $bytes_uploaded . ' rows=' . $rows . ' mysqli_err=' . $err );
    }

    /**
     * Delete the media upload checkpoint from wp_options on successful job completion.
     */
    private static function _delete_media_checkpoint( string $job_id ): void {
        global $wpdb;
        $sql = $wpdb->prepare(
            "DELETE FROM {$wpdb->options} WHERE option_name = %s",
            self::_ckpt_option_key( $job_id )
        );
        mysqli_query( $wpdb->dbh, $sql );
    }

    /**
     * Validate that a SAS URL is HTTPS to prevent SSRF via HTTP downgrade.
     *
     * @param string $sas_url
     * @throws Exception if URL is not HTTPS
     */
    private static function _validate_sas_url( string $sas_url ): void {
        if ( empty( $sas_url ) ) {
            throw new Exception( 'SAS URL is empty.' );
        }
        if ( 0 !== strpos( $sas_url, 'https://' ) ) {
            throw new Exception( 'SAS URL must use HTTPS.' );
        }
        // Basic host check — must point to .blob.core.windows.net
        $host = parse_url( $sas_url, PHP_URL_HOST );
        if ( false === strpos( $host, '.blob.core.windows.net' ) ) {
            throw new Exception( "SAS URL host is not a trusted Azure Blob endpoint: {$host}" );
        }
    }
}
