<?php
/**
 * KloudStack Migration — Background Export Engine
 *
 * Manages async jobs for DB dump and per-file media upload to Azure Blob Storage.
 * Uses WP-Cron for scheduling: process_queue() runs every 60 seconds.
 *
 * Job lifecycle:
 *   queued → processing → complete | failed
 *
 * DB export:
 *   1. Shell-out to mysqldump --single-transaction --quick (respects WP DB constants)
 *   2. Write raw SQL to a temp file (no gzip — avoids CPU spike on shared hosting)
 *   3. Upload the SQL dump to Azure Blob via SAS PUT request
 *   4. Update job transient → complete
 *
 * Media upload (per-file streaming — Sprint M):
 *   1. Enumerate all files in wp-content/uploads/ recursively
 *   2. For each file: cURL PUT directly to Azure Blob using a container-level SAS token
 *      — no ZIP, no /tmp disk usage, no compression
 *   3. Track uploaded files in the job transient for resume-on-retry (checkpointed)
 *   4. After all files: upload a _manifest.json blob to signal completion
 *   5. Update job transient → complete
 *
 * Content export (plugins / themes / mu-plugins / custom-root):
 *   1. Create a ZIP archive of the source directory
 *   2. Stream upload to Azure Blob via SAS PUT request
 *   3. Update job transient → complete
 *
 * Security:
 *   - mysqldump credentials taken from WP_DB_* constants (never user input)
 *   - Command arguments individually escaped with escapeshellarg()
 *   - SAS URLs and SAS tokens validated to be HTTPS / Azure Blob endpoints before use
 *   - Temp files created in sys_get_temp_dir() with unique names and deleted after use
 *
 * @package KloudStackMigration
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class KloudStack_Migration_BackgroundExport {

    const CRON_HOOK    = 'kloudstack_process_export_queue';
    const QUEUE_OPTION = 'kloudstack_export_queue';

    // Max concurrent jobs processed per cron tick
    const MAX_JOBS_PER_RUN = 1;

    // Chunk size for streaming upload: 4 MB
    const UPLOAD_CHUNK_SIZE = 4 * 1024 * 1024;

    // ------------------------------------------------------------------
    // Cron setup
    // ------------------------------------------------------------------

    public static function setup_cron(): void {
        if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
            wp_schedule_event( time(), 'every_minute', self::CRON_HOOK );
        }
        add_filter( 'cron_schedules', [ __CLASS__, 'add_cron_interval' ] );
        add_action( self::CRON_HOOK, [ __CLASS__, 'process_queue' ] );
    }

    public static function add_cron_interval( array $schedules ): array {
        if ( ! isset( $schedules['every_minute'] ) ) {
            $schedules['every_minute'] = [
                'interval' => 60,
                'display'  => 'Every Minute',
            ];
        }
        return $schedules;
    }

    // ------------------------------------------------------------------
    // Queue management
    // ------------------------------------------------------------------

    /**
     * Enqueue a new export job.
     *
     * @param string $job_id     Unique job ID (generated by RestEndpoints)
     * @param string $type       'db_export' | 'media_upload' | 'content_export'
     * @param string $sas_url    Azure Blob SAS URL for uploading
     * @param array  $extra_data Additional fields to store in the queue item (e.g. source_path, artifact)
     */
    public static function enqueue( string $job_id, string $type, string $sas_url, array $extra_data = [] ): void {
        $queue   = get_option( self::QUEUE_OPTION, [] );
        $queue[] = array_merge(
            [
                'job_id'  => $job_id,
                'type'    => $type,
                'sas_url' => $sas_url,
            ],
            $extra_data
        );
        update_option( self::QUEUE_OPTION, $queue, false );
    }

    /**
     * Process the next job(s) from the queue.
     * Called by WP-Cron every minute.
     */
    public static function process_queue(): void {
        // Prevent concurrent execution. The shutdown function registered by export_db /
        // upload_media and WP-Cron can both fire process_queue() at the same time.
        // A transient-based mutex stops double-processing and double resource usage.
        $lock_key = 'ks_mig_queue_lock';
        if ( get_transient( $lock_key ) ) {
            return; // Another invocation is already running — skip silently
        }
        // TTL = 10 min. Auto-expires if the process is killed before the finally block.
        set_transient( $lock_key, 1, 600 );

        try {
            $queue = get_option( self::QUEUE_OPTION, [] );
            if ( empty( $queue ) ) {
                return;
            }

            $processed = 0;
            $remaining = [];

            foreach ( $queue as $item ) {
                if ( $processed >= self::MAX_JOBS_PER_RUN ) {
                    $remaining[] = $item;
                    continue;
                }

                $job_id  = $item['job_id'];
                $type    = $item['type'];
                $sas_url = $item['sas_url'];

                // Load agent-provided hints stored when the job was queued.
                // On retries after a failure the backend may include adjusted parameters
                // (e.g. stream_rate_limit_kbps after a CPU spike or skip_extensions after an OOM).
                $job_transient = get_transient( KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id );
                $hints = ( is_array( $job_transient ) && isset( $job_transient['hints'] ) && is_array( $job_transient['hints'] ) )
                    ? $job_transient['hints']
                    : [];

                // Mark as processing
                self::_update_job( $job_id, [ 'status' => 'processing', 'progress' => 5 ] );

                $success = false;
                try {
                    if ( 'db_export' === $type ) {
                        $success = self::_run_db_export( $job_id, $sas_url, $hints );
                    } elseif ( 'media_stream' === $type ) {
                        $container_base_url = $item['container_base_url'] ?? '';
                        $blob_prefix        = $item['blob_prefix'] ?? '';
                        $sas_token          = $item['sas_token'] ?? '';
                        $success = self::_run_media_stream( $job_id, $container_base_url, $blob_prefix, $sas_token, $hints );
                    } elseif ( 'media_upload' === $type ) {
                        // Legacy job type — kept for any jobs queued before Sprint M.
                        $success = self::_run_media_upload( $job_id, $sas_url, $hints );
                    } elseif ( 'content_export' === $type ) {
                        $source_path = $item['source_path'] ?? '';
                        $success = self::_run_content_export( $job_id, $sas_url, $source_path, $hints );
                    }
                } catch ( Exception $e ) {
                    self::_update_job( $job_id, [
                        'status' => 'failed',
                        'error'  => substr( $e->getMessage(), 0, 500 ),
                    ] );
                    error_log( "KloudStack Migration: job {$job_id} failed: " . $e->getMessage() );
                }

                if ( $success ) {
                    self::_update_job( $job_id, [ 'status' => 'complete', 'progress' => 100 ] );
                } elseif ( 'failed' !== self::_job_status( $job_id ) ) {
                    $remaining[] = $item; // Re-queue if not explicitly marked failed
                }

                $processed++;
            }

            update_option( self::QUEUE_OPTION, $remaining, false );
        } finally {
            delete_transient( $lock_key );
        }
    }

    // ------------------------------------------------------------------
    // DB Export
    // ------------------------------------------------------------------

    /**
     * Export the WordPress database to a plain SQL dump and upload to Azure Blob.
     *
     * Streams mysqldump output to a temp file without gzip compression.
     * --single-transaction avoids table locks on InnoDB (zero impact on the live site).
     * --quick reads one row at a time, keeping memory usage minimal on shared hosting.
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool  true on success
     * @throws Exception  on mysqldump failure or upload failure
     */
    private static function _run_db_export( string $job_id, string $sas_url, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        // exec() is required for mysqldump. Available by default on Azure App Service
        // Linux, but may be disabled on some shared hosting environments.
        if ( ! function_exists( 'exec' ) ) {
            throw new Exception( 'Database export requires exec() which is not available on this server. Contact your hosting provider.' );
        }

        // Apply optional stream rate limit hint (kbps). When the agent detects high CPU
        // during export it may set stream_rate_limit_kbps to throttle the mysqldump pipe.
        $rate_limit_kbps = isset( $hints['stream_rate_limit_kbps'] ) ? max( 128, (int) $hints['stream_rate_limit_kbps'] ) : 0;

        $tmp_file = tempnam( sys_get_temp_dir(), 'ks_db_' ) . '.sql';

        try {
            // Build mysqldump command with individual argument escaping.
            // --single-transaction: InnoDB snapshot — zero table locking, invisible to other connections.
            // --quick: reads one row at a time — minimal RAM on restricted shared hosting accounts.
            // --routines --triggers --add-drop-table: full schema + data export.
            $host     = escapeshellarg( DB_HOST );
            $user     = escapeshellarg( DB_USER );
            $database = escapeshellarg( DB_NAME );
            $tmp_esc  = escapeshellarg( $tmp_file );

            // DB_PASSWORD is passed via env var to avoid appearing on process list
            putenv( 'MYSQL_PWD=' . DB_PASSWORD );

            if ( $rate_limit_kbps > 0 ) {
                // pv throttles the byte rate of the pipe when a CPU limit hint is active.
                // Falls back gracefully if pv is not installed (most shared hosts lack it).
                $pv_available = ! empty( shell_exec( 'which pv 2>/dev/null' ) );
                if ( $pv_available ) {
                    $rate_arg = escapeshellarg( $rate_limit_kbps . 'k' );
                    $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                         . "--quick --routines --triggers --add-drop-table {$database} "
                         . "| pv -q -L {$rate_arg} > {$tmp_esc} 2>/dev/null'";
                } else {
                    $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                         . "--quick --routines --triggers --add-drop-table {$database} "
                         . "> {$tmp_esc} 2>/dev/null'";
                }
            } else {
                $cmd = "bash -c 'mysqldump --host={$host} --user={$user} --single-transaction "
                     . "--quick --routines --triggers --add-drop-table {$database} "
                     . "> {$tmp_esc} 2>/dev/null'";
            }

            $output    = [];
            $exit_code = 0;
            exec( $cmd, $output, $exit_code );

            // Clear password from environment immediately
            putenv( 'MYSQL_PWD=' );

            if ( 0 !== $exit_code ) {
                throw new Exception( 'mysqldump failed (exit=' . $exit_code . '): ' . implode( ' ', $output ) );
            }

            if ( ! file_exists( $tmp_file ) || 0 === filesize( $tmp_file ) ) {
                throw new Exception( 'mysqldump produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 70 ] );

            // Upload plain SQL to Azure Blob via SAS PUT
            self::_upload_file_to_blob( $sas_url, $tmp_file, 'application/octet-stream' );

            self::_update_job( $job_id, [ 'progress' => 100 ] );
            return true;

        } finally {
            // Always clean up temp file
            if ( file_exists( $tmp_file ) ) {
                unlink( $tmp_file );
            }
            putenv( 'MYSQL_PWD=' );
        }
    }

    // ------------------------------------------------------------------
    // Media Stream — per-file direct Blob PUT (Sprint M)
    // ------------------------------------------------------------------

    /**
     * Stream every file in wp-content/uploads/ directly to Azure Blob Storage.
     *
     * Each file is PUT individually using a container-level SAS token — no ZIP,
     * no temp disk usage. The job transient tracks uploaded files so that a
     * retry/WP-Cron resumption skips already-completed files (checkpointing).
     *
     * A _manifest.json blob is uploaded as the final step to signal completion.
     *
     * @param string $job_id
     * @param string $container_base_url  e.g. https://{account}.blob.core.windows.net/kloudstack-migrations
     * @param string $blob_prefix         e.g. migrations/{id}/media/uploads
     * @param string $sas_token           Container-level write SAS (no leading '?')
     * @param array  $hints               Agent-provided hints (skip_extensions, max_file_size_mb)
     * @return bool  true when all files uploaded and manifest written
     * @throws Exception on unrecoverable upload failure
     */
    private static function _run_media_stream(
        string $job_id,
        string $container_base_url,
        string $blob_prefix,
        string $sas_token,
        array $hints = []
    ): bool {
        // Validate the container base URL points to Azure Blob Storage over HTTPS.
        if ( 0 !== strpos( $container_base_url, 'https://' ) ) {
            throw new Exception( 'container_base_url must use HTTPS.' );
        }
        if ( false === strpos( parse_url( $container_base_url, PHP_URL_HOST ) ?? '', '.blob.core.windows.net' ) ) {
            throw new Exception( 'container_base_url host is not a trusted Azure Blob endpoint.' );
        }

        $uploads_dir = wp_upload_dir();
        $base_dir    = $uploads_dir['basedir'];

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Uploads directory not found: {$base_dir}" );
        }

        // Agent hints.
        $skip_extensions = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;

        // Batch size: number of files processed per WP-Cron tick.
        // Keeps each execution under ~8 minutes on slow shared hosting
        // (500 files × ~100 ms/HTTPS PUT = ~50 s, well within safe limits).
        $batch_size = 500;

        // Load checkpoint — list of relative paths already uploaded this job.
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job_data      = get_transient( $transient_key );
        $uploaded      = isset( $job_data['uploaded_files'] ) && is_array( $job_data['uploaded_files'] )
            ? $job_data['uploaded_files']
            : [];
        $uploaded_set  = array_flip( $uploaded ); // O(1) lookups

        // Build the full file list (only built once; subsequent batches use transient offset).
        $all_files = [];
        $iterator  = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
            RecursiveIteratorIterator::LEAVES_ONLY
        );
        foreach ( $iterator as $file ) {
            if ( ! $file->isFile() ) {
                continue;
            }
            if ( $skip_extensions ) {
                $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                    continue;
                }
            }
            if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                continue;
            }
            $all_files[] = [
                'abs'  => $file->getPathname(),
                'rel'  => str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() ),
                'size' => $file->getSize(),
            ];
        }

        $total_files = count( $all_files );
        $total_bytes = array_sum( array_column( $all_files, 'size' ) );

        // Update totals in transient so the polling loop can display accurate counts.
        self::_update_job( $job_id, [
            'total_files'  => $total_files,
            'total_bytes'  => $total_bytes,
        ] );

        $files_this_batch = 0;

        foreach ( $all_files as $entry ) {
            $rel_path = $entry['rel'];

            // Skip files already uploaded (checkpointing — safe to resume after PHP-FPM kill).
            if ( isset( $uploaded_set[ $rel_path ] ) ) {
                continue;
            }

            // Normalise path separators to forward-slash for the blob name.
            $blob_rel  = str_replace( DIRECTORY_SEPARATOR, '/', $rel_path );
            $blob_name = "{$blob_prefix}/{$blob_rel}";
            $blob_url  = "{$container_base_url}/{$blob_name}?{$sas_token}";

            // Detect MIME type for accurate Content-Type header.
            $mime_type = 'application/octet-stream';
            if ( function_exists( 'mime_content_type' ) ) {
                $detected = mime_content_type( $entry['abs'] );
                if ( $detected ) {
                    $mime_type = $detected;
                }
            }

            self::_upload_blob_put( $blob_url, $entry['abs'], $mime_type );

            // Record as uploaded in checkpoint.
            $uploaded[]              = $rel_path;
            $uploaded_set[$rel_path] = true;
            $files_this_batch++;

            // Persist checkpoint and progress after each file.
            $progress = $total_files > 0
                ? min( 99, (int) ( count( $uploaded ) / $total_files * 99 ) )
                : 99;
            self::_update_job( $job_id, [
                'progress'       => $progress,
                'files_uploaded' => count( $uploaded ),
                'bytes_uploaded' => array_sum(
                    array_map(
                        fn( $r ) => $all_files[ array_search( $r, array_column( $all_files, 'rel' ), true ) ]['size'] ?? 0,
                        $uploaded
                    )
                ),
                'uploaded_files' => $uploaded,
            ] );

            // Yield after the batch limit to allow WP-Cron to reschedule.
            if ( $files_this_batch >= $batch_size ) {
                // Mark job as still processing (not failed) and exit cleanly.
                // WP-Cron will re-enqueue this job on the next tick and resume
                // from the checkpoint transient.
                self::_update_job( $job_id, [ 'status' => 'processing' ] );
                return false; // Returning false re-queues the item for the next cron tick.
            }
        }

        // All files uploaded — write _manifest.json as the completion signal.
        $manifest = json_encode( [
            'total_files'  => $total_files,
            'total_bytes'  => $total_bytes,
            'completed_at' => time(),
        ] );
        // Build the manifest blob URL — strip /uploads suffix from the prefix so
        // the manifest lands at the container root for that migration, not inside /uploads.
        $media_base   = preg_replace( '#/uploads$#', '', $blob_prefix );
        $manifest_url = "{$container_base_url}/{$media_base}/_manifest.json?{$sas_token}";

        $tmp_manifest = tempnam( sys_get_temp_dir(), 'ks_manifest_' ) . '.json';
        try {
            file_put_contents( $tmp_manifest, $manifest );
            self::_upload_blob_put( $manifest_url, $tmp_manifest, 'application/json' );
        } finally {
            if ( file_exists( $tmp_manifest ) ) {
                unlink( $tmp_manifest );
            }
        }

        self::_update_job( $job_id, [
            'progress'       => 100,
            'files_uploaded' => $total_files,
            'bytes_uploaded' => $total_bytes,
        ] );

        return true;
    }

    // ------------------------------------------------------------------
    // Media Upload — legacy ZIP approach (kept for backward compat)
    // ------------------------------------------------------------------

    /**
     * Create a ZIP of wp-content/uploads and upload to Azure Blob.
     * Kept for any jobs queued before Sprint M. New jobs use _run_media_stream().
     *
     * @param string $job_id
     * @param string $sas_url  Must be HTTPS
     * @return bool
     * @throws Exception
     */
    private static function _run_media_upload( string $job_id, string $sas_url, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        if ( ! class_exists( 'ZipArchive' ) ) {
            throw new Exception( 'PHP ZipArchive extension is not available.' );
        }

        $uploads_dir = wp_upload_dir();
        $base_dir    = $uploads_dir['basedir'];

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Uploads directory not found: {$base_dir}" );
        }

        // Agent hints: skip files by extension or size on retry attempts.
        // These are applied when a previous attempt timed out due to large video/archive files.
        $skip_extensions   = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;  // 0 = no limit

        $tmp_zip = tempnam( sys_get_temp_dir(), 'ks_media_' ) . '.zip';

        try {
            $zip = new ZipArchive();
            if ( true !== $zip->open( $tmp_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
                throw new Exception( "Cannot create ZIP archive at {$tmp_zip}" );
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
                RecursiveIteratorIterator::LEAVES_ONLY
            );

            $file_count = 0;
            foreach ( $iterator as $file ) {
                if ( $file->isFile() ) {
                    // Apply agent hints: skip by extension and/or file size.
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }

                    $relative_path = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() );
                    $zip->addFile( $file->getPathname(), $relative_path );
                    $file_count++;

                    // Update progress periodically during the zip phase (5–55%).
                    // ZipArchive::addFile() only stores the path reference — actual
                    // file data is compressed at close() time, so no memory flush
                    // is needed here.
                    if ( 0 === $file_count % 100 ) {
                        self::_update_job( $job_id, [ 'progress' => min( 55, 5 + (int) ( $file_count / 20 ) ) ] );
                    }
                }
            }

            $zip->close();

            if ( ! file_exists( $tmp_zip ) || 0 === filesize( $tmp_zip ) ) {
                throw new Exception( 'ZIP archive creation produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 65 ] );

            // Upload to Azure Blob via SAS PUT
            self::_upload_file_to_blob( $sas_url, $tmp_zip, 'application/zip' );

            return true;

        } finally {
            if ( file_exists( $tmp_zip ) ) {
                unlink( $tmp_zip );
            }
        }
    }

    // ------------------------------------------------------------------
    // Content export helper (plugins / themes / media / mu-plugins / custom-root)
    // ------------------------------------------------------------------

    /**
     * ZIP the given source directory and upload to Azure Blob via SAS URL.
     *
     * Special value 'custom-root': exports only root-level files from WP_CONTENT_DIR,
     * excluding standard sub-directories (plugins, themes, uploads, mu-plugins,
     * languages, upgrade).
     *
     * @param string $job_id      Job transient key
     * @param string $sas_url     Azure Blob SAS PUT URL
     * @param string $source_path Absolute path, or 'custom-root' sentinel
     * @param array  $hints       Optional skip_extensions / max_file_size_mb
     * @throws Exception on filesystem or upload failure
     */
    private static function _run_content_export( string $job_id, string $sas_url, string $source_path, array $hints = [] ): bool {
        self::_validate_sas_url( $sas_url );

        if ( ! class_exists( 'ZipArchive' ) ) {
            throw new Exception( 'PHP ZipArchive extension is not available.' );
        }

        $skip_extensions = isset( $hints['skip_extensions'] ) && is_array( $hints['skip_extensions'] )
            ? array_map( 'strtolower', $hints['skip_extensions'] )
            : [];
        $max_size_bytes  = isset( $hints['max_file_size_mb'] ) && $hints['max_file_size_mb'] > 0
            ? ( (int) $hints['max_file_size_mb'] ) * 1024 * 1024
            : 0;

        $is_custom_root = ( 'custom-root' === $source_path );
        $base_dir       = $is_custom_root ? WP_CONTENT_DIR : $source_path;

        if ( ! is_dir( $base_dir ) ) {
            throw new Exception( "Source directory does not exist: {$base_dir}" );
        }

        // Sub-directories to exclude when scanning WP_CONTENT_DIR root.
        $excluded_subdirs = [ 'plugins', 'themes', 'uploads', 'mu-plugins', 'languages', 'upgrade' ];

        // WordPress drop-in files are environment-specific: they contain connection
        // credentials, paths, and configuration for the SOURCE server.  Copying them
        // to the target stack causes PHP fatal errors (e.g. W3TC's db.php calling
        // wp_get_wp_version() before WordPress has finished bootstrapping).
        // Exclude them here — caching plugins will regenerate correct drop-ins for
        // the target environment when they are re-enabled after migration.
        $excluded_root_files = [
            'db.php',
            'advanced-cache.php',
            'object-cache.php',
            'db-error.php',
            'maintenance.php',
        ];

        $tmp_zip = tempnam( sys_get_temp_dir(), 'ks_content_' ) . '.zip';

        try {
            $zip = new ZipArchive();
            if ( true !== $zip->open( $tmp_zip, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
                throw new Exception( "Cannot create ZIP archive at {$tmp_zip}" );
            }

            $file_count = 0;

            if ( $is_custom_root ) {
                // Only root-level files in WP_CONTENT_DIR; skip standard sub-directories.
                $dir_iter = new DirectoryIterator( $base_dir );
                foreach ( $dir_iter as $file ) {
                    if ( $file->isDot() ) {
                        continue;
                    }
                    if ( $file->isDir() ) {
                        if ( in_array( $file->getFilename(), $excluded_subdirs, true ) ) {
                            continue;
                        }
                        // Non-standard sub-directory: include recursively.
                        $sub_iter = new RecursiveIteratorIterator(
                            new RecursiveDirectoryIterator( $file->getPathname(), FilesystemIterator::SKIP_DOTS ),
                            RecursiveIteratorIterator::LEAVES_ONLY
                        );
                        foreach ( $sub_iter as $sub_file ) {
                            if ( ! $sub_file->isFile() ) {
                                continue;
                            }
                            if ( $skip_extensions ) {
                                $ext = strtolower( pathinfo( $sub_file->getFilename(), PATHINFO_EXTENSION ) );
                                if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                                    continue;
                                }
                            }
                            if ( $max_size_bytes > 0 && $sub_file->getSize() > $max_size_bytes ) {
                                continue;
                            }
                            $relative = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $sub_file->getPathname() );
                            $zip->addFile( $sub_file->getPathname(), $relative );
                            $file_count++;
                        }
                        continue;
                    }
                    // Root-level file.
                    if ( in_array( $file->getFilename(), $excluded_root_files, true ) ) {
                        continue;
                    }
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }
                    $zip->addFile( $file->getPathname(), $file->getFilename() );
                    $file_count++;
                }
            } else {
                $iterator = new RecursiveIteratorIterator(
                    new RecursiveDirectoryIterator( $base_dir, FilesystemIterator::SKIP_DOTS ),
                    RecursiveIteratorIterator::LEAVES_ONLY
                );
                foreach ( $iterator as $file ) {
                    if ( ! $file->isFile() ) {
                        continue;
                    }
                    if ( $skip_extensions ) {
                        $ext = strtolower( pathinfo( $file->getFilename(), PATHINFO_EXTENSION ) );
                        if ( in_array( '.' . $ext, $skip_extensions, true ) || in_array( $ext, $skip_extensions, true ) ) {
                            continue;
                        }
                    }
                    if ( $max_size_bytes > 0 && $file->getSize() > $max_size_bytes ) {
                        continue;
                    }
                    $relative = str_replace( $base_dir . DIRECTORY_SEPARATOR, '', $file->getPathname() );
                    $zip->addFile( $file->getPathname(), $relative );
                    $file_count++;
                    if ( 0 === $file_count % 100 ) {
                        self::_update_job( $job_id, [ 'progress' => min( 55, 5 + (int) ( $file_count / 20 ) ) ] );
                    }
                }
            }

            $zip->close();

            if ( ! file_exists( $tmp_zip ) || 0 === filesize( $tmp_zip ) ) {
                throw new Exception( 'ZIP archive creation produced empty output.' );
            }

            self::_update_job( $job_id, [ 'progress' => 65 ] );
            self::_upload_file_to_blob( $sas_url, $tmp_zip, 'application/zip' );

            return true;

        } finally {
            if ( file_exists( $tmp_zip ) ) {
                unlink( $tmp_zip );
            }
        }
    }

    // ------------------------------------------------------------------
    // Azure Blob upload helpers
    // ------------------------------------------------------------------

    /**
     * Upload a local file to an Azure Blob using a SAS PUT URL.
     *
     * Includes x-ms-version (unlocks 5 GB single PUT), x-ms-blob-content-md5
     * (Azure verifies integrity on ingest), and accurate Content-Type per file.
     * Uses cURL streaming PUT to avoid loading the file into PHP memory.
     *
     * @param string $sas_url    Full blob SAS URL (must be HTTPS)
     * @param string $local_path Full filesystem path to the file
     * @param string $mime_type  MIME type for Content-Type header
     * @throws Exception on upload failure
     */
    private static function _upload_blob_put( string $sas_url, string $local_path, string $mime_type ): void {
        $file_size = filesize( $local_path );
        $fh        = fopen( $local_path, 'rb' );

        if ( false === $fh ) {
            throw new Exception( "Cannot open file for upload: {$local_path}" );
        }

        try {
            // Compute MD5 for server-side integrity verification.
            // Azure rejects the PUT with HTTP 400 if the hash doesn't match.
            $md5_b64 = base64_encode( hash_file( 'md5', $local_path, true ) );

            $ch = curl_init( $sas_url );
            curl_setopt_array( $ch, [
                CURLOPT_PUT            => true,
                CURLOPT_INFILE         => $fh,
                CURLOPT_INFILESIZE     => $file_size,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => 3600,
                CURLOPT_HTTPHEADER     => [
                    'Content-Type: ' . $mime_type,
                    'x-ms-blob-type: BlockBlob',
                    'x-ms-version: 2021-06-08',     // unlocks 5 GB single PUT limit
                    'x-ms-blob-content-md5: ' . $md5_b64,
                    'Expect:',                       // suppress 100-Continue delay with Azure
                ],
            ] );

            $body      = curl_exec( $ch );
            $http_code = (int) curl_getinfo( $ch, CURLINFO_HTTP_CODE );
            $curl_err  = curl_error( $ch );
            curl_close( $ch );

            if ( $curl_err ) {
                throw new Exception( 'cURL upload error: ' . $curl_err );
            }

            if ( $http_code < 200 || $http_code >= 300 ) {
                throw new Exception( "Azure Blob upload failed (HTTP {$http_code}): " . substr( (string) $body, 0, 300 ) );
            }
        } finally {
            fclose( $fh );
        }
    }

    /**
     * Backward-compat wrapper used by _run_db_export and _run_content_export.
     * Delegates to _upload_blob_put — kept so callers don't need updating.
     */
    private static function _upload_file_to_blob( string $sas_url, string $local_path, string $mime_type ): void {
        self::_upload_blob_put( $sas_url, $local_path, $mime_type );
    }

    // ------------------------------------------------------------------
    // Job helpers
    // ------------------------------------------------------------------

    private static function _update_job( string $job_id, array $updates ): void {
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job           = get_transient( $transient_key );
        if ( false === $job ) {
            return;
        }
        $job = array_merge( $job, $updates );
        set_transient( $transient_key, $job, KloudStack_Migration_RestEndpoints::JOB_TTL );
    }

    private static function _job_status( string $job_id ): string {
        $transient_key = KloudStack_Migration_RestEndpoints::JOB_TRANSIENT_PREFIX . $job_id;
        $job           = get_transient( $transient_key );
        return $job['status'] ?? 'unknown';
    }

    /**
     * Validate that a SAS URL is HTTPS to prevent SSRF via HTTP downgrade.
     *
     * @param string $sas_url
     * @throws Exception if URL is not HTTPS
     */
    private static function _validate_sas_url( string $sas_url ): void {
        if ( empty( $sas_url ) ) {
            throw new Exception( 'SAS URL is empty.' );
        }
        if ( 0 !== strpos( $sas_url, 'https://' ) ) {
            throw new Exception( 'SAS URL must use HTTPS.' );
        }
        // Basic host check — must point to .blob.core.windows.net
        $host = parse_url( $sas_url, PHP_URL_HOST );
        if ( false === strpos( $host, '.blob.core.windows.net' ) ) {
            throw new Exception( "SAS URL host is not a trusted Azure Blob endpoint: {$host}" );
        }
    }
}
